'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Apply

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''firstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents firstName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''requiredFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents requiredFirstName As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lastName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''requiredLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents requiredLastName As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents email As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''requiredEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents requiredEmail As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''phoneNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phoneNumber As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''requiredPhoneNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents requiredPhoneNumber As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''mailingStreetAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mailingStreetAddress As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''requiredMailingStreetAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents requiredMailingStreetAddress As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''mailingCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mailingCity As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''requiredMailingCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents requiredMailingCity As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''mailingState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mailingState As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''requiredMailingState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents requiredMailingState As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''mailingZipCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mailingZipCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''requiredMailingZipCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents requiredMailingZipCode As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''birthMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents birthMonth As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''requiredBirthMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents requiredBirthMonth As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''birthDay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents birthDay As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''requiredBirthDay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents requiredBirthDay As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''birthYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents birthYear As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''requiredBirthYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents requiredBirthYear As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''sex control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sex As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''requiredSex control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents requiredSex As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''gpa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gpa As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''requiredGPA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents requiredGPA As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''firstToAttendCollege control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents firstToAttendCollege As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''requiredFirstToAttendCollege control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents requiredFirstToAttendCollege As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''schoolAttending control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents schoolAttending As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''requiredSchoolAttending control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents requiredSchoolAttending As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''schoolCityStateAttending control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents schoolCityStateAttending As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''requiredSchoolCityStateAttending control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents requiredSchoolCityStateAttending As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''academicHonors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents academicHonors As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''nonAcademicAwards control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents nonAcademicAwards As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''membershipActivities control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents membershipActivities As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hobbiesOutsideInterests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hobbiesOutsideInterests As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''extracurricularActivites control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents extracurricularActivites As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''schoolRelatedVolunteerActivites control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents schoolRelatedVolunteerActivites As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''collegeWillAttend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents collegeWillAttend As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''collegeChoiceOne control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents collegeChoiceOne As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''collegeChoiceTwo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents collegeChoiceTwo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''collegeChoiceThree control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents collegeChoiceThree As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''employeeOfHano control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents employeeOfHano As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''requiredEmployeeOfHano control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents requiredEmployeeOfHano As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''parentOrLegalGuardianFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents parentOrLegalGuardianFirstName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''parentOrLegalGuardianLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents parentOrLegalGuardianLastName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''parentOrLegalGuardianStreetAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents parentOrLegalGuardianStreetAddress As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''parentOrLegalGuardianCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents parentOrLegalGuardianCity As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''parentOrLegalGuardianState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents parentOrLegalGuardianState As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''parentOrLegalGuardianZipCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents parentOrLegalGuardianZipCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''parentOrLegalGuardianHomePhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents parentOrLegalGuardianHomePhone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''parentOrLegalGuardianWorkPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents parentOrLegalGuardianWorkPhone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''essaySubmisison control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents essaySubmisison As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''requiredEssaySubmisison control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents requiredEssaySubmisison As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''transcriptSupportStatement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents transcriptSupportStatement As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''requiredTranscriptSupportStatement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents requiredTranscriptSupportStatement As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''signatureOfScholarshipApplicant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents signatureOfScholarshipApplicant As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''requiredSignatureOfScholarshipApplicant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents requiredSignatureOfScholarshipApplicant As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''signatureOfScholarshipApplicantDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents signatureOfScholarshipApplicantDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents button As Global.System.Web.UI.HtmlControls.HtmlButton
End Class
